export interface SelectOption {
  value: string
  label: string
}

export const categoryOptions: SelectOption[] = [
  { value: 'normal', label: '普通女孩' },
  { value: 'supermodel', label: '时尚超模' },
  { value: 'kardashian', label: '卡戴珊风格' },
  { value: 'sweet_cool', label: '甜酷风' },
  { value: 'intellectual', label: '知性风' },
  { value: 'fresh', label: '清纯风' },
  { value: 'sporty', label: '运动风' },
  { value: 'vintage', label: '复古风' },
  { value: 'high_street', label: '商业街拍' },
]

export const ageOptions: SelectOption[] = [
  { value: '16', label: '16岁' },
  { value: '18', label: '18岁' },
  { value: '20', label: '20岁' },
  { value: '22', label: '22岁' },
  { value: '25', label: '25岁' },
  { value: '28', label: '28岁' },
  { value: '30', label: '30岁' },
  { value: '35', label: '35岁' },
  { value: '40', label: '40岁' },
  { value: '45', label: '45岁' },
  { value: '50', label: '50岁' },
]

export const ethnicityOptions: SelectOption[] = [
  { value: 'Chinese', label: '中国人' },
  { value: 'Korean', label: '韩国人' },
  { value: 'Japanese', label: '日本人' },
  { value: 'Southeast_Asian', label: '东南亚人' },
  { value: 'Thai', label: '泰国人' },
  { value: 'Indian', label: '印度人' },
  { value: 'Middle_Eastern', label: '中东人' },
  { value: 'American', label: '美国人' },
  { value: 'British', label: '英国人' },
  { value: 'French', label: '法国人' },
  { value: 'Italian', label: '意大利人' },
  { value: 'Spanish', label: '西班牙人' },
  { value: 'Russian', label: '俄罗斯人' },
  { value: 'Brazilian', label: '巴西人' },
  { value: 'African', label: '非洲人' },
  { value: 'Mixed', label: '混血' },
]

export const genderOptions: SelectOption[] = [
  { value: 'female', label: '女性' },
  { value: 'male', label: '男性' },
  { value: 'androgynous', label: '中性' },
]

export const skinOptions: SelectOption[] = [
  { value: 'porcelain', label: '瓷白' },
  { value: 'fair', label: '白皙' },
  { value: 'light', label: '浅肤色' },
  { value: 'natural', label: '自然肤色' },
  { value: 'olive', label: '橄榄色' },
  { value: 'tan', label: '小麦色' },
  { value: 'caramel', label: '焦糖色' },
  { value: 'deep', label: '深肤色' },
  { value: 'ebony', label: '乌木色' },
]

export const bodyOptions: SelectOption[] = [
  { value: 'petite', label: '娇小' },
  { value: 'slim', label: '修长' },
  { value: 'athletic', label: '匀称健美' },
  { value: 'average', label: '标准' },
  { value: 'curvy', label: '曲线' },
  { value: 'plus', label: '丰满' },
  { value: 'muscular', label: '肌肉型' },
]

export const heightOptions: SelectOption[] = [
  { value: '', label: '不指定' },
  { value: 'petite', label: '娇小 ~155cm' },
  { value: 'short', label: '偏矮 ~160cm' },
  { value: 'medium', label: '中等 ~165cm' },
  { value: 'tall', label: '高挑 ~172cm' },
  { value: 'very_tall', label: '超高 ~178cm+' },
]

export const faceShapeOptions: SelectOption[] = [
  { value: '', label: '不指定' },
  { value: 'oval', label: '鹅蛋脸' },
  { value: 'round', label: '圆脸' },
  { value: 'heart', label: '心形脸' },
  { value: 'square', label: '方脸' },
  { value: 'diamond', label: '菱形脸' },
  { value: 'oblong', label: '长脸' },
  { value: 'v_shaped', label: 'V 型脸' },
]

export const hairStyleOptions: SelectOption[] = [
  { value: '', label: '不指定' },
  { value: 'straight_long', label: '长直发' },
  { value: 'straight_medium', label: '中长直发' },
  { value: 'straight_short', label: '短直发' },
  { value: 'wavy_long', label: '长卷发' },
  { value: 'wavy_medium', label: '中长卷发' },
  { value: 'curly_long', label: '长大卷' },
  { value: 'curly_short', label: '短卷发' },
  { value: 'bob', label: '齐下巴短发 (Bob)' },
  { value: 'lob', label: '齐肩中短发 (Lob)' },
  { value: 'pixie', label: '超短发 (Pixie)' },
  { value: 'bangs_straight', label: '齐刘海直发' },
  { value: 'bangs_curtain', label: '法式刘海' },
  { value: 'ponytail_high', label: '高马尾' },
  { value: 'ponytail_low', label: '低马尾' },
  { value: 'bun_high', label: '高丸子头' },
  { value: 'bun_messy', label: '慵懒丸子头' },
  { value: 'braids', label: '编发' },
  { value: 'half_up', label: '半扎发' },
  { value: 'side_part', label: '侧分发' },
  { value: 'center_part', label: '中分发' },
  { value: 'wet_look', label: '湿发背梳' },
  { value: 'afro', label: '自然蓬松卷 (Afro)' },
  { value: 'shaved', label: '超短寸头' },
]

export const hairColorOptions: SelectOption[] = [
  { value: '', label: '不指定' },
  { value: 'black', label: '黑色' },
  { value: 'dark_brown', label: '深棕色' },
  { value: 'brown', label: '棕色' },
  { value: 'light_brown', label: '浅棕/栗色' },
  { value: 'ash', label: '灰棕/亚麻色' },
  { value: 'honey', label: '蜜糖金' },
  { value: 'blonde', label: '金色' },
  { value: 'platinum', label: '铂金/银白' },
  { value: 'red', label: '红棕色' },
  { value: 'ginger', label: '姜铜色' },
  { value: 'ombre', label: '渐变色' },
  { value: 'highlights', label: '挑染高光' },
  { value: 'pink', label: '粉色' },
  { value: 'blue', label: '蓝色' },
  { value: 'gray', label: '自然灰白' },
]

export const faceFeatureOptions: SelectOption[] = [
  { value: '', label: '无（自由发挥）' },
  { value: 'American makeup style with contoured cheekbones, bold brows, nude or red lips, highlighted nose bridge, full coverage matte foundation（美式妆造）', label: '美式妆造' },
  { value: 'Korean makeup style with gradient lips, straight brows, dewy glass skin, subtle eyeliner, natural flush cheeks（韩式妆造）', label: '韩式妆造' },
  { value: 'Japanese soft-focus makeup with warm rosy cheeks, under-eye blush, natural thin brows, glossy lips（日系妆造）', label: '日系妆造' },
  { value: 'Chinese classical beauty makeup: red lips, sharply defined brow arch, porcelain-smooth skin, subtle winged eyeliner（中式古典妆）', label: '中式古典妆' },
  { value: 'European high-fashion editorial makeup: sculpted cheeks, bold lip color, strong brow, dramatic lashes（欧美高定妆）', label: '欧美高定妆' },
  { value: 'Bare-face no-makeup look: completely clean natural skin, no cosmetics at all, raw authentic beauty（素颜）', label: '素颜' },
  { value: 'light natural freckles across nose and cheeks, sun-kissed fresh face, minimal makeup（轻微雀斑）', label: '轻微雀斑' },
  { value: 'Sharp cat-eye eyeliner with bold winged tips, dramatic lashes, slightly smoky（猫眼妆）', label: '猫眼妆' },
  { value: 'Smoky eye makeup with dark blended eyeshadow, kohl-lined waterline, nude lips（烟熏妆）', label: '烟熏妆' },
  { value: 'Glowy dewy glass-skin finish with highlighter on cheekbones, nose, and cupid bow（水光肌）', label: '水光肌' },
  { value: 'Mole/beauty mark near the lip or cheek, adding a distinctive charm point（美人痣）', label: '美人痣' },
  { value: 'Dimples visible when smiling, adding youthful charm to the face（酒窝）', label: '酒窝' },
]

export const poseOptions: SelectOption[] = [
  { value: '', label: '无（自由发挥）' },
  { value: 'walking confidently（自信地行走）', label: '自信地行走' },
  { value: 'standing with hands on hips（双手叉腰站立）', label: '双手叉腰站立' },
  { value: 'sitting elegantly（优雅地坐着）', label: '优雅地坐着' },
  { value: 'leaning against a wall（靠墙站立）', label: '靠墙站立' },
  { value: 'turning around（转身）', label: '转身' },
  { value: 'looking over shoulder（回头凝视）', label: '回头凝视' },
  { value: 'hands in pockets（双手插兜）', label: '双手插兜' },
  { value: 'arms crossed（双臂交叉）', label: '双臂交叉' },
  { value: 'walking towards camera（朝镜头走来）', label: '朝镜头走来' },
  { value: 'walking away from camera（背对镜头走开）', label: '背对镜头走开' },
  { value: 'adjusting clothes（整理衣物）', label: '整理衣物' },
  { value: 'holding a bag（手提包）', label: '手提包' },
  { value: 'checking phone（看手机）', label: '看手机' },
  { value: 'putting on sunglasses（戴墨镜）', label: '戴墨镜' },
  { value: 'looking at watch（看手表）', label: '看手表' },
  { value: 'stretching arms（伸展双臂）', label: '伸展双臂' },
  { value: 'dancing gracefully（优雅地舞蹈）', label: '优雅地舞蹈' },
  { value: 'running dynamically（动态奔跑）', label: '动态奔跑' },
  { value: 'jumping joyfully（欢快跳跃）', label: '欢快跳跃' },
  { value: 'sitting on stairs（坐在台阶上）', label: '坐在台阶上' },
  { value: 'lying on grass（躺在草地上）', label: '躺在草地上' },
  { value: 'kneeling down（跪下）', label: '跪下' },
  { value: 'crouching（蹲着）', label: '蹲着' },
  { value: 'leaning forward（身体前倾）', label: '身体前倾' },
  { value: 'tilting head（歪头）', label: '歪头' },
  { value: 'raising one hand（举起一只手）', label: '举起一只手' },
  { value: 'pointing somewhere（指向某处）', label: '指向某处' },
  { value: 'clapping hands（拍手）', label: '拍手' },
  { value: 'holding coffee cup（端着咖啡杯）', label: '端着咖啡杯' },
  { value: 'tying shoelaces（系鞋带）', label: '系鞋带' },
  { value: 'power pose with legs apart（棚拍分腿力量站姿）', label: '棚拍分腿力量站姿' },
  { value: 'hand on waist chin up（棚拍叉腰仰头）', label: '棚拍叉腰仰头' },
  { value: 'sitting on stool legs crossed（棚拍坐凳翘腿）', label: '棚拍坐凳翘腿' },
  { value: 'one arm raised behind head（棚拍单臂举过头顶）', label: '棚拍单臂举过头顶' },
  { value: 'dramatic lean on prop table（棚拍斜靠道具桌）', label: '棚拍斜靠道具桌' },
  { value: 'profile pose looking away（棚拍侧脸凝视远方）', label: '棚拍侧脸凝视远方' },
  { value: 'high fashion hand near face（棚拍手部靠近面部）', label: '棚拍手部靠近面部' },
  { value: 'contrapposto with hand in hair（棚拍对位站姿手撩发）', label: '棚拍对位站姿手撩发' },
  { value: 'kneeling on one knee arm extended（棚拍单膝跪地手臂伸展）', label: '棚拍单膝跪地手臂伸展' },
  { value: 'back-to-camera over shoulder glance（棚拍背对镜头回眸）', label: '棚拍背对镜头回眸' },
]

export const expressionOptions: SelectOption[] = [
  { value: '', label: '无（自由发挥）' },
  { value: 'natural smile（自然微笑）', label: '自然微笑' },
  { value: 'confident smile（自信微笑）', label: '自信微笑' },
  { value: 'gentle smile（温柔微笑）', label: '温柔微笑' },
  { value: 'mysterious smile（神秘微笑）', label: '神秘微笑' },
  { value: 'playful smile（俏皮微笑）', label: '俏皮微笑' },
  { value: 'serious expression（严肃表情）', label: '严肃表情' },
  { value: 'thoughtful look（沉思表情）', label: '沉思表情' },
  { value: 'surprised look（惊讶表情）', label: '惊讶表情' },
  { value: 'happy and joyful（开心愉悦）', label: '开心愉悦' },
  { value: 'calm and peaceful（平静安详）', label: '平静安详' },
  { value: 'dreamy gaze（梦幻眼神）', label: '梦幻眼神' },
  { value: 'intense gaze（深情注视）', label: '深情注视' },
  { value: 'shy smile（害羞微笑）', label: '害羞微笑' },
  { value: 'laughing heartily（开怀大笑）', label: '开怀大笑' },
  { value: 'subtle smirk（微微撇嘴）', label: '微微撇嘴' },
  { value: 'cool and aloof（冷酷高冷）', label: '冷酷高冷' },
  { value: 'warm and friendly（温暖友善）', label: '温暖友善' },
  { value: 'elegant composure（优雅端庄）', label: '优雅端庄' },
  { value: 'curious look（好奇表情）', label: '好奇表情' },
  { value: 'relaxed and casual（轻松随意）', label: '轻松随意' },
]
